### PR TITLE
Refactored the file output code

### PR DESCRIPTION
**Pull request by chalkers**
I refactored the `defaultValues` inside the `generateFileOutput` code. Made it so that the `writeFileSync` call is simpler.

### CODE REVIEW

**Comment by kenwalger** [comment]
Is it just a style standard to have:

function BasicManager()  no space between name and parenthesis, but:

BasicManager.... = function (...) space between function and parenthesis

**Comment by chalkers** [comment]
Oops, I ran Webstorm's code formatter, to indent the code, I didn't notice it added spaces there, I don't like it. Feel free to remove the space :)

**Comment by kenwalger** [comment]
Great. Thanks for your experienced eyeballs on this. I'll put the other two functions, connect(), and isAdHocNetwork() on my TODO list.

**Comment by chalkers** [comment]
You know what though...

Because they are anonymous function you could write them like


BasicManager.prototype.blah = function fooBar() {

}

**Pull request merged**
